# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodTraveler' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #pod 'FBSDKCoreKit'
  #pod 'FBSDKLoginKit'
  #pod 'FBSDKShareKit'

  pod 'FBSDKCoreKit', '~> 4.40.0'
  pod 'FBSDKLoginKit', '~> 4.40.0'
  pod 'FBSDKShareKit', '~> 4.40.0'
  
 # Pods for FoodTraveler

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  #pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'FoodTravelerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FoodTraveler-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FoodTraveler-tvOS

  target 'FoodTraveler-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
